language: python

python:
  - 3.4

install: python setup.py install

script:
  - mkdir ../html_out
  - pixelpitch-html ../html_out

after_success:
  - openssl aes-256-cbc -K $encrypted_deecc27f1e75_key -iv $encrypted_deecc27f1e75_iv -in travis/gh_deploy_key.enc -out travis/gh_deploy_key -d
  - chmod 600 travis/gh_deploy_key
  - eval `ssh-agent -s`
  - ssh-add travis/gh_deploy_key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd ..
  - git clone -b gh-pages git@github.com:letmaik/pixelpitch.git gh-pages
  - mv html_out/* gh-pages
  - cd gh-pages
  - git config user.name "Travis"
  - git config user.email "travis@travis-ci.org"
  - git add .
  - git commit -m 'automated commit'
  - git push origin gh-pages
