sudo: false

language: python

python: 3.5

install: python setup.py install

script:
  - mkdir html_out
  - pixelpitch-html html_out

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: html_out
  on:
    branch: master