name: main

on:
  push:
    branches: [ master ]

  workflow_dispatch:

  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run script
      run: |
        python pixelpitch.py

    - name: Upload CSV artifact
      uses: actions/upload-artifact@v4
      with:
        name: camera-data.csv
        path: dist/result.csv

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
