name: update and deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

  schedule:
    - cron:  '0 0 1 * *'

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  update:
    runs-on: [self-hosted, mac0]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt

    - name: Run script
      run: |
        python3 pixelpitch.py

    - name: Commit and push camera data
      run: |
        git config --local user.email "hletrd@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git add -f dist/camera-data.csv
        git commit -m "Update camera-data.csv [skip ci]" || exit 0
        git push

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/

    - name: Deploy
      uses: actions/deploy-pages@v4
